version: "3"

volumes:
  db:
      driver: local

services:
  database:
    image: postgres:14-alpine
    hostname: florgon-api
    restart: always
    volumes:
      - ../db:/var/lib/postgresql/data
    env_file: 
      - .database.env
  server:
    hostname: florgon-api
    restart: always
    env_file:
      - .server.env
    volumes:
      - ./api:/srv/www/florgon/api
    ports:
      - "${COMPOSE_EXPOSED_PORT}:80"
    depends_on:
      - database
    links:
      - database
    build: .