version: "3"

volumes:
  db:
      driver: local

services:
  database:
    image: postgres:14-alpine
    hostname: florgon-auth-api
    restart: always
    volumes:
      - ../db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_NAME=auth-api
      - POSTGRES_USER=auth-api
      - POSTGRES_PASSWORD=postgres
  server:
    hostname: florgon-auth-api
    restart: always
    volumes:
      - ./auth-api:/srv/www/florgon/auth-api
    ports:
      - "80:80"
    depends_on:
      - database
    links:
      - database
    build: .
    command: python3 main.py