name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  unittests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker
      working-directory: ./src
      run: docker-compose up -d
    - name: Pytest
      working-directory: ./src/api/app
      run: docker run --network container:florgon-api-server pytest
